services:
- docker
install: make build
stages:
- name: echo
- name: publish
  if: branch = master AND type != pull_request
jobs:
  include:
  - stage: echo
    script: echo
  - stage: publish
    name: Publish production image
    script:
    - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
    - make publish
env:
  global:
  - secure: p58YOLjnq/OAuJE4E3/6VhIaOG+cpUplC9fIccV5rwbB7QZXbh/ODv1V4wpuyleToRTRZkwngTc/o59qNfC2FRWEiumcWAXPNzh/fkwixYy0nBMSCAIzamlymICyccuw13nCx+vWho6QrZ/sOq7GIrluBO54OUXHKlnNLQS0FO+RRZQZKPYl/G3RjHwZF703qNUd18p5hJwR0bYDYgEnW8JMGWGeicOrWcCC0+7y3iai0JbOjaxPjhQHAJgo6AKjv45kMVB/0ANWXb0AjREt1X8WlD/HfJ+mF4w1SpDxPDILRULPmbzIV/wRSxTCqvjYOoWFENYkZxvwITvdnUCbP2G3Eu4CWDXWfY1KkOaw+LUfvuhIlXm344yd7JK5/2DQIhtfIouBlPj9DbZAwtGu0KTnA3KvuTVfy1wKVDyXWjrRoEO/g6S8Yh0rcLmoA35eExYET7NpkKSKVUEIhklP/PHJvkmmsIvPpf/BzANzfna1lYHrIdcwFShLayY1VV+IXCiRhM1K8iwu3IGn5WZ6oaAH+ycnJcu7BI7hLONt53/GDgTQs5k2P6erFVEJkkCZVDwicYBRMzP9rEx6bT+0nOXKM83guqZThPGomH1O8JdJzh0PoTNq7n3k+D8bdeZ+anNBF3bcrP9Guy/wZOhwOwUtkd/ofjIsc7j7IuVcXqw=
  - secure: WMi4G2hdG6tK1UPCg+6qI5yosa0lVQZhaDBK4AoKVj54z+rrN8hNS7/5puyGXQ7fhtKixPm358sFcHyXkneSgls22Qzn86Fbx0lonna96vUUAki4o4xGXzX6rtr1z2/IIuN4KqGj7wuYgopt+1IZE9NkdYSfujfXY+wdozrrkj5SoGgeopguUG9+MyGGjwvWXRd0Q3f7UmWSW/w5M8JmvnAgOhTffLRSNGUIgtD0Od4woyRPZZxR/1Hj3/as25/YXJpfqh9Khbdhn+QfnngzvHaVFGLthSD6ADs2N2+OiyxfX1jQCpksEuBtcWHCQpLqa1iOFGRysD7/bDYO019G7CahsJIyK4rHZrAaFMR+AE6kISUYK/QX67SYR7T4m46SE9KY57MXZp9Uwr+cWUjbIGWiDnGgNUEP6MxKwGpFwcTd+xp+PsblpDZtehfNGS+XSjYcnI35Z6pUObJo21NXi7r0tihkLk7kydT/tkdJhTQD6b9Y5XIRUdjttujoA8NytLl40Z0qKBybKeQE5tzMzl90NwFm4T9b5dN52QVE4cYb5QpTZXUvWJnoGz2ojU8zKKdPPRxG2rfAPLgtIR6Ovwe55cOYE2RU2/zBwKZ+Eqo5xuGiZtohbwya5XMg+KOLBYDeE3yrouKAIUt/hAvXzknvJ3x42KMhvLuyQoxgsss=
